### ISSUE TITLE
deployment on engineyard

### ISSUE THREAD

**Issue by nqzero** [engineyard/chat#3] opened 2017-06-27 00:05 UTC
i signed up for a trial on engineyard and am trying to deploy this sample app to understand the deploy process (as suggested in the getting started document). i provided the git url and left more settings at default, though i changed to "no database" since redis wasn't on the list

i'm getting 500 errors when i try to access the demo app

is there a document that describes how to get this demo running on engineyard ? or is this configuration with node.js and redis no longer supported ?

**Comment by ghost** [comment] 2017-06-28 12:05
Hey nqzero,

Will from Engine Yard here.  I just looked into your environment and it appears that the issue is due to the stack selected.  The environment is configured to use stack v2, which is an extremely old version of the stack (the latest release is version 5).  Many node versions are not available on v2 since it is so old.

In reality, the main reason for the 500's is that the application failed to deploy.  The application was expecting a node version that is not available on v2.  Switching to v5 would certainly solve the issue you're seeing here.

To directly answer your question, we do have documentation on how to deploy a node application here: https://support.cloud.engineyard.com/hc/en-us/articles/205411878-Deploy-Your-Node-js-Application-on-Engine-Yard-Cloud

You can find all the supported versions in the latest stack (v5) on the following doc: https://support.cloud.engineyard.com/hc/en-us/articles/222896468-Engine-Yard-Gentoo-16-06-Technology-Stack

**Comment by ghost** [comment] 2017-06-29 14:54
Closing issue.  Feel free to reopen if you would like to discuss further.

**Closed as completed by ghost** 2017-06-29 14:54 UTC
Labels: question
